# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10000)),
                ('last_name', models.CharField(blank=True, max_length=10000)),
                ('user_name', models.CharField(max_length=1111121)),
                ('user_id', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1231312312312312313)),
                ('meaning', models.CharField(max_length=1231312312312312313)),
                ('last_review', models.TimeField()),
                ('last_review_status', models.BooleanField(default=False)),
                ('teleuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.TeleUser')),
            ],
        ),
    ]
