# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170513_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='last_review',
            new_name='next_review_time',
        ),
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
