# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20170514_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='wrong_answer',
            field=models.IntegerField(default=0),
        ),
    ]
