# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20170517_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=1111121),
        ),
    ]
